from private import TWITTER_KEY, TWITTER_SECRET, TWITTER_APP_KEY, TWITTER_APP_SECRET, CONNECTION_STRING

TRACK_COLLECTION_NAME = 'candidates'
RAW_COLLECTION_NAME = 'raw_tweets'
ROLLUP_COLLECTION_NAME = 'rollup_data'
PROCESSED_COLLECTION_NAME = 'processed_stats'
